export const ADD_COURSE = 'ADD_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const EDIT_COURSE = 'EDIT_COURSE';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const SEARCH_COURSES = 'SEARCH_COURSES';
export const SET_COURSES = 'SET_COURSES';
export const EXERCISE_STATUS = 'EXERCISE_STATUS';
export const EDIT_EXERCISE = 'EDIT_EXERCISE';
export const SET_CHOOSE_FRIENDS = "SET_CHOOSE_FRIENDS";

